# Generated by Django 5.2.3 on 2025-06-26 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
    ]
